# Generated by Django 3.0.2 on 2020-01-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='newsitem',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
